GRID_SIZE = 58  # 20% larger than previous
MIN_RECT_SIZE = 1
ENTITY_SIZE = 44  # Keep entity size same (fits in 58px grid with margin)
LABEL_OFFSET_Y = -18
HP_BAR_RATIO = 0.12
HP_BAR_OFFSET = 4
DOOR_WIDTH_RATIO = 0.6
DOOR_HEIGHT_RATIO = 0.18
PILLAR_RATIO = 0.7
ENCOUNTER_SPACING = 1.2

ROLE_KIND = 0
ROLE_LABEL = 1
ROLE_LOCKED = 2
ROLE_STATUS = 3
ROLE_ICON = 4
ROLE_HP = 5
ROLE_SHOW_HP = 6
ROLE_AC = 7
ROLE_LABEL_ITEM = 20
ROLE_ICON_ITEM = 21
ROLE_HP_BG = 22
ROLE_HP_FG = 23
ROLE_AC_ITEM = 24
ROLE_LAYER = 25
ROLE_OWNER_PLAYER_ID = 26
ROLE_ENTITY_ID = 27
ROLE_LINKED_SHEET_ID = 28
ROLE_LINKED_SHEET_NAME = 29
ROLE_LINKED_CHARACTER_ID = 30

LAYER_BG = "background"
LAYER_MID = "middle"
LAYER_FG = "foreground"

TOOL_SELECT = "select"
TOOL_ROOM = "room"
TOOL_POLYGON = "polygon"
TOOL_CORRIDOR = "corridor"
TOOL_DOOR = "door"
TOOL_PILLAR = "pillar"
TOOL_MONSTER = "monster"
TOOL_PLAYER = "player"
TOOL_ENCOUNTER = "encounter"
TOOL_WALL = "wall"
TOOL_FLOOR = "floor"
TOOL_ELLIPSE = "ellipse"
TOOL_PING = "ping"
TOOL_FOW_BRUSH = "fow_brush"
TOOL_FOW_ERASER = "fow_eraser"

LAYER_GEOMETRY = {TOOL_ROOM, TOOL_POLYGON, TOOL_CORRIDOR, TOOL_WALL, TOOL_FLOOR, TOOL_ELLIPSE}
LAYER_STRUCTURES = {TOOL_DOOR, TOOL_PILLAR}
LAYER_ENTITIES = {TOOL_MONSTER, TOOL_PLAYER}

# Styling Constants
WALL_COLOR = "#334155"
WALL_WIDTH = 6
FLOOR_COLOR = "#94a3b8"
